export const CONNECT_TO_WHATSAPP_FACTORY = 'CONNECT_TO_WHATSAPP_FACTORY';

export const CREATE_CLIENT_FACTORY = 'CREATE_CLIENT_FACTORY';

export const CREATE_USER_FACTORY = 'CREATE_USER_FACTORY';
export const LOAD_USER_BY_EMAIL_FACTORY = 'LOAD_USER_BY_EMAIL_FACTORY';
