export const CONNECT_TO_WHATSAPP_FACTORY = 'CONNECT_TO_WHATSAPP_FACTORY';

export const CREATE_CLIENT_FACTORY = 'CREATE_CLIENT_FACTORY';

export const CREATE_USER_FACTORY = 'CREATE_USER_FACTORY';
export const LOAD_USER_BY_EMAIL_FACTORY = 'LOAD_USER_BY_EMAIL_FACTORY';

export const AUTHENTICATION_FACTORY = 'AUTHENTICATION_FACTORY';

export const CREATE_CHANNEL_FACTORY = 'CREATE_CHANNEL_FACTORY';

export const CREATE_USER_CHANNEL_FACTORY = 'CREATE_USER_CHANNEL_FACTORY';

export const EMIT_MESSAGES_FACTORY = 'EMIT_MESSAGES_FACTORY';

export const CREATE_CHAT_FACTORY = 'CREATE_CHAT_FACTORY';
export const ATTACH_CHAT_TO_USER_FACTORY = 'ATTACH_CHAT_TO_USER_FACTORY';
